In [25]:
import numpy as np
import pandas as pd

In [26]:
df = pd.read_csv('../data/welm_pdx.csv')
print('Number of rows: ' + str(len(df)))
num_sample_drug_replicate = len(df[['Sample', 'Drug', 'Replicate Number']].drop_duplicates())
print('Number of mice: ' + str(num_sample_drug_replicate))

Number of rows: 5955
Number of mice: 399

In [27]:
df.head()

,Day,Drug,Other Info,Replicate Number,Sample,Tumor Volume mm3,source_file,excel_sheet
0,1.0,Navitoclax,NaN,M0,HCI-010,163.920800,43018_2022_337_MOESM7_ESM.xlsx,6d left
1,4.0,Navitoclax,NaN,M0,HCI-010,158.374381,43018_2022_337_MOESM7_ESM.xlsx,6d left
2,8.0,Navitoclax,NaN,M0,HCI-010,197.154048,43018_2022_337_MOESM7_ESM.xlsx,6d left
3,11.0,Navitoclax,NaN,M0,HCI-010,158.582177,43018_2022_337_MOESM7_ESM.xlsx,6d left
4,15.0,Navitoclax,NaN,M0,HCI-010,176.645000,43018_2022_337_MOESM7_ESM.xlsx,6d left

### Give each Sample-Drug-Replicate Number a unique MID

In [28]:
def enumerate_mid_names(mid_names):
    mid_dict = {}
    for x in range(0, len(mid_names)):
        mid_dict[mid_names[x]] = x
    return mid_dict

old_len = len(df)
# Assign each Sample-Drug-Replicate an MID
df = df.merge(df.groupby(['Sample', 'Drug', 'Replicate Number']).apply(lambda x: x.name).reset_index(name='MID'), 
              on=['Sample', 'Drug', 'Replicate Number'], 
              validate='many_to_one')

In [29]:
mid_names = df['MID'].unique()

In [30]:
mid_dict = enumerate_mid_names(df['MID'].unique())
df['MID'] = df['MID'].map(mid_dict)

In [20]:
assert df.MID.nunique() == num_sample_drug_replicate
assert len(df) == old_len

### Rename and select columns

In [6]:
df = df.rename(columns = {'Tumor Volume mm3': 'Volume'})
cols = ['MID', 'Sample', 'Drug', 'Day', 'Volume']
df_out = df[cols]
df_out.head()

   MID   Sample        Drug   Day      Volume
0    0  HCI-010  Navitoclax   1.0  163.920800
1    0  HCI-010  Navitoclax   4.0  158.374381
2    0  HCI-010  Navitoclax   8.0  197.154048
3    0  HCI-010  Navitoclax  11.0  158.582177
4    0  HCI-010  Navitoclax  15.0  176.645000

In [7]:
df_out.to_csv('../data/welm_pdx_w_mid.csv', index=False)

### Investigating odd MIDs

In [33]:
d = pd.read_csv('../data/welm_pdx.csv')
d.head()

,Day,Drug,Other Info,Replicate Number,Sample,Tumor Volume mm3,source_file,excel_sheet
0,1.0,Navitoclax,NaN,M0,HCI-010,163.920800,43018_2022_337_MOESM7_ESM.xlsx,6d left
1,4.0,Navitoclax,NaN,M0,HCI-010,158.374381,43018_2022_337_MOESM7_ESM.xlsx,6d left
2,8.0,Navitoclax,NaN,M0,HCI-010,197.154048,43018_2022_337_MOESM7_ESM.xlsx,6d left
3,11.0,Navitoclax,NaN,M0,HCI-010,158.582177,43018_2022_337_MOESM7_ESM.xlsx,6d left
4,15.0,Navitoclax,NaN,M0,HCI-010,176.645000,43018_2022_337_MOESM7_ESM.xlsx,6d left

In [32]:
mid_names[21]

('HCI-015', 'Vehicle', 'M0')

In [36]:
s = d.loc[(d['Sample'] == 'HCI-015') & (d['Drug'] == 'Vehicle') & (d['Replicate Number'] == 'M0')]
s

,Day,Drug,Other Info,Replicate Number,Sample,Tumor Volume mm3,source_file,excel_sheet
144,1.0,Vehicle,NaN,M0,HCI-015,138.915000,43018_2022_337_MOESM7_ESM.xlsx,6d mid
145,4.0,Vehicle,NaN,M0,HCI-015,145.330504,43018_2022_337_MOESM7_ESM.xlsx,6d mid
146,8.0,Vehicle,NaN,M0,HCI-015,182.656688,43018_2022_337_MOESM7_ESM.xlsx,6d mid
147,11.0,Vehicle,NaN,M0,HCI-015,203.187798,43018_2022_337_MOESM7_ESM.xlsx,6d mid
148,15.0,Vehicle,NaN,M0,HCI-015,306.954364,43018_2022_337_MOESM7_ESM.xlsx,6d mid
149,18.0,Vehicle,NaN,M0,HCI-015,338.624248,43018_2022_337_MOESM7_ESM.xlsx,6d mid
150,22.0,Vehicle,NaN,M0,HCI-015,389.207000,43018_2022_337_MOESM7_ESM.xlsx,6d mid
396,1.0,Vehicle,NaN,M0,HCI-015,138.915000,43018_2022_337_MOESM7_ESM.xlsx,6f top right
397,4.0,Vehicle,NaN,M0,HCI-015,145.330504,43018_2022_337_MOESM7_ESM.xlsx,6f top right
398,8.0,Vehicle,NaN,M0,HCI-015,182.656688,43018_2022_337_MOESM7_ESM.xlsx,6f top right
399,11.0,Vehicle,NaN,M0,HCI-015,203.187798,43018_2022_337_MOESM7_ESM.xlsx,6f top right
400,15.0,Vehicle,NaN,M0,HCI-015,306.954364,43018_2022_337_MOESM7_ESM.xlsx,6f top right
401,18.0,Vehicle,NaN,M0,HCI-015,338.624248,43018_2022_337_MOESM7_ESM.xlsx,6f top right
402,22.0,Vehicle,NaN,M0,HCI-015,389.207000,43018_2022_337_MOESM7_ESM.xlsx,6f top right
3162,1.0,Vehicle,NaN,M0,HCI-015,55.072640,43018_2022_337_MOESM9_ESM.xlsx,7d left
3163,4.0,Vehicle,NaN,M0,HCI-015,83.815910,43018_2022_337_MOESM9_ESM.xlsx,7d left
3164,8.0,Vehicle,NaN,M0,HCI-015,156.212537,43018_2022_337_MOESM9_ESM.xlsx,7d left
3165,11.0,Vehicle,NaN,M0,HCI-015,222.499238,43018_2022_337_MOESM9_ESM.xlsx,7d left
3166,15.0,Vehicle,NaN,M0,HCI-015,301.175963,43018_2022_337_MOESM9_ESM.xlsx,7d left
3167,18.0,Vehicle,NaN,M0,HCI-015,326.538149,43018_2022_337_MOESM9_ESM.xlsx,7d left
3168,22.0,Vehicle,NaN,M0,HCI-015,334.857259,43018_2022_337_MOESM9_ESM.xlsx,7d left

In [37]:
mid_names[24]

('HCI-015', 'Vehicle', 'M3')

In [38]:
f = d.loc[(d['Sample'] == 'HCI-015') & (d['Drug'] == 'Vehicle') & (d['Replicate Number'] == 'M3')]
f

,Day,Drug,Other Info,Replicate Number,Sample,Tumor Volume mm3,source_file,excel_sheet
165,1.0,Vehicle,NaN,M3,HCI-015,130.235000,43018_2022_337_MOESM7_ESM.xlsx,6d mid
166,4.0,Vehicle,NaN,M3,HCI-015,101.713030,43018_2022_337_MOESM7_ESM.xlsx,6d mid
167,8.0,Vehicle,NaN,M3,HCI-015,133.490286,43018_2022_337_MOESM7_ESM.xlsx,6d mid
168,11.0,Vehicle,NaN,M3,HCI-015,123.037704,43018_2022_337_MOESM7_ESM.xlsx,6d mid
169,15.0,Vehicle,NaN,M3,HCI-015,106.660069,43018_2022_337_MOESM7_ESM.xlsx,6d mid
170,18.0,Vehicle,NaN,M3,HCI-015,135.502848,43018_2022_337_MOESM7_ESM.xlsx,6d mid
171,22.0,Vehicle,NaN,M3,HCI-015,106.170500,43018_2022_337_MOESM7_ESM.xlsx,6d mid
417,1.0,Vehicle,NaN,M3,HCI-015,130.235000,43018_2022_337_MOESM7_ESM.xlsx,6f top right
418,4.0,Vehicle,NaN,M3,HCI-015,101.713030,43018_2022_337_MOESM7_ESM.xlsx,6f top right
419,8.0,Vehicle,NaN,M3,HCI-015,133.490286,43018_2022_337_MOESM7_ESM.xlsx,6f top right
420,11.0,Vehicle,NaN,M3,HCI-015,123.037704,43018_2022_337_MOESM7_ESM.xlsx,6f top right
421,15.0,Vehicle,NaN,M3,HCI-015,106.660069,43018_2022_337_MOESM7_ESM.xlsx,6f top right
422,18.0,Vehicle,NaN,M3,HCI-015,135.502848,43018_2022_337_MOESM7_ESM.xlsx,6f top right
423,22.0,Vehicle,NaN,M3,HCI-015,106.170500,43018_2022_337_MOESM7_ESM.xlsx,6f top right
3183,1.0,Vehicle,NaN,M3,HCI-015,113.380067,43018_2022_337_MOESM9_ESM.xlsx,7d left
3184,4.0,Vehicle,NaN,M3,HCI-015,126.181042,43018_2022_337_MOESM9_ESM.xlsx,7d left
3185,8.0,Vehicle,NaN,M3,HCI-015,159.621050,43018_2022_337_MOESM9_ESM.xlsx,7d left
3186,11.0,Vehicle,NaN,M3,HCI-015,166.874429,43018_2022_337_MOESM9_ESM.xlsx,7d left
3187,15.0,Vehicle,NaN,M3,HCI-015,237.931017,43018_2022_337_MOESM9_ESM.xlsx,7d left
3188,18.0,Vehicle,NaN,M3,HCI-015,273.291679,43018_2022_337_MOESM9_ESM.xlsx,7d left
3189,22.0,Vehicle,NaN,M3,HCI-015,372.764401,43018_2022_337_MOESM9_ESM.xlsx,7d left