In [16]:
import numpy as np
import pickle

def read_pickle(fn):
    with open(fn, 'rb') as handle:
        obj = pickle.load(handle)
    return obj

In [17]:
fn = '../fold_info/fold_list.pkl'
folds = read_pickle(fn)
folds[0]

array([251, 181, 165,  19, 263, 208,  13, 259, 162, 215, 104, 167,   8,
       294, 211, 134])

In [18]:
folds[1]

array([138, 183,  41,  12,  90, 282,  16,   4, 237, 198,  64, 290, 288,
       253, 118,  48])

In [19]:
for fold in folds:
    print(len(fold))

16
16
16
16
16
15
16
16
16
16
16
16
16
16
15
16
16
16
16
16

In [20]:
print(len(folds))

20

In [29]:
for fold in folds:
    print(fold)

[251 181 165  19 263 208  13 259 162 215 104 167   8 294 211 134]
[138 183  41  12  90 282  16   4 237 198  64 290 288 253 118  48]
[ 15 130 135 312 270 171 280  70 302 157  56 170 295  32  39  81]
[293  78 124 160 189  65 153 115 225 109  38 297 298  74 240  89]
[217 193 213 182 309 279 158 219   9  33 128 242 201 176  98  69]
[218 123 119 178 286 212  83 190  18  91 269  17  86 252 154]
[187 221 172  73  55 258  85 159  31 204 300 117 143  35  57  37]
[ 34   1 161 210 227 301 243 206 303 150 260 147 169 317  72 314]
[ 95  25 281 224 133 186 247 311 108 244 310 235 234 112 121  22]
[ 42 261 254  93 200  88 155  50  80   2 168  54  66 296  26 241]
[287  96 106 272  84 144 256 231 278 145 156 257  51 146  61  68]
[ 79 129  43  67 202 125 265 166  36 276  97  45 305 139  53 194]
[230 114 268  60 180 308 148  24 177 175 141  52 315 228 262 142]
[222 184 232 102  77 236 274 304 306 277  27  20 199 100  94 127]
[ 23 209  21 122 149 266  29 246 233 131  46 205 185  82 195]
[226 207 163 151 196 101  71 307 267 271 216   6 179 120 255 188]
[299 197 250  14   3  28 113  92 292  58 173 137 214 229  47 174]
[291 283  10  30 191 289 152 203 248 273 140 116   0 285 238 103]
[  7 284  99 164  62 264 239 105 107 223  76 126 275 249  44  59]
[136 111  49 313   5 110 192 220 245 316 132  40  75  87  63  11]

In [30]:
import pandas as pd
data_fn = '../data/rep-gdsc-ctd2-mean-log.csv'
df = pd.read_csv(data_fn)
df.head()

,Drug.Name,ccle,drug_id,sample_id,REP_published_auc_mean,CTD2_published_auc_mean,GDSC_published_auc_mean,REP_auc_overlap_mean,CTD2_auc_overlap_mean,GDSC_auc_overlap_mean,log_REP_published_auc_mean,log_CTD2_published_auc_mean,log_GDSC_published_auc_mean,log_REP_auc_overlap_mean,log_CTD2_auc_overlap_mean,log_GDSC_auc_overlap_mean
0,MASITINIB,MFE296,0,0,2.418060,0.254280,0.593273,0.912542,0.593923,0.868955,1.591848,0.302591,0.457048,0.654899,0.468167,0.554420
1,MASITINIB,PSN1,0,1,2.723739,0.825330,0.308393,0.912542,0.754841,0.873705,1.722505,0.726041,0.312686,0.654899,0.559771,0.556469
2,MASITINIB,KYSE150,0,2,1.806341,0.863541,0.783193,0.912542,0.754000,0.818837,1.306098,0.752933,0.548257,0.654899,0.559299,0.532672
3,MASITINIB,ESS1,0,3,1.939192,0.590966,0.213433,0.912542,0.717525,0.700777,1.371203,0.557295,0.262369,0.654899,0.538754,0.480509
4,MASITINIB,A172,0,4,2.821828,0.849530,0.308393,0.912542,0.749597,0.875567,1.762925,0.743093,0.312686,0.654899,0.556826,0.557272

In [41]:
for i in range(0, len(folds)):
    f = folds[i]
    s = df.loc[df.sample_id.isin(f)]
    print(len(s))

872
856
814
806
842
845
911
768
815
856
835
852
856
806
791
779
820
777
870
817

In [42]:
print(len(folds))

20

In [37]:
df.head()

,Drug.Name,ccle,drug_id,sample_id,REP_published_auc_mean,CTD2_published_auc_mean,GDSC_published_auc_mean,REP_auc_overlap_mean,CTD2_auc_overlap_mean,GDSC_auc_overlap_mean,log_REP_published_auc_mean,log_CTD2_published_auc_mean,log_GDSC_published_auc_mean,log_REP_auc_overlap_mean,log_CTD2_auc_overlap_mean,log_GDSC_auc_overlap_mean
0,MASITINIB,MFE296,0,0,2.418060,0.254280,0.593273,0.912542,0.593923,0.868955,1.591848,0.302591,0.457048,0.654899,0.468167,0.554420
1,MASITINIB,PSN1,0,1,2.723739,0.825330,0.308393,0.912542,0.754841,0.873705,1.722505,0.726041,0.312686,0.654899,0.559771,0.556469
2,MASITINIB,KYSE150,0,2,1.806341,0.863541,0.783193,0.912542,0.754000,0.818837,1.306098,0.752933,0.548257,0.654899,0.559299,0.532672
3,MASITINIB,ESS1,0,3,1.939192,0.590966,0.213433,0.912542,0.717525,0.700777,1.371203,0.557295,0.262369,0.654899,0.538754,0.480509
4,MASITINIB,A172,0,4,2.821828,0.849530,0.308393,0.912542,0.749597,0.875567,1.762925,0.743093,0.312686,0.654899,0.556826,0.557272

In [39]:
s = df.loc[df.sample_id.isin(f0)]
s.head()

,Drug.Name,ccle,drug_id,sample_id,REP_published_auc_mean,CTD2_published_auc_mean,GDSC_published_auc_mean,REP_auc_overlap_mean,CTD2_auc_overlap_mean,GDSC_auc_overlap_mean,log_REP_published_auc_mean,log_CTD2_published_auc_mean,log_GDSC_published_auc_mean,log_REP_auc_overlap_mean,log_CTD2_auc_overlap_mean,log_GDSC_auc_overlap_mean
8,MASITINIB,8MGBA,0,8,1.968746,0.905149,0.260913,0.912542,0.755160,0.848828,1.385442,0.782025,0.287672,0.654899,0.559950,0.545714
13,MASITINIB,SNGM,0,13,3.367426,0.476331,0.118473,0.912542,0.742926,0.808576,1.975794,0.472266,0.210868,0.654899,0.553075,0.528190
19,MASITINIB,CAL51,0,19,1.443428,0.472085,0.735713,0.912542,0.683075,0.575833,1.118387,0.469084,0.525809,0.654899,0.519232,0.423816
104,MASITINIB,SNU407,0,104,2.764514,0.096763,0.118473,0.912542,0.524799,0.745663,1.739392,0.178012,0.210868,0.654899,0.428022,0.500498
134,MASITINIB,A101D,0,134,1.513445,-0.037402,0.735713,0.912542,-0.189015,0.876201,1.155798,0.068962,0.525809,0.654899,-0.017947,0.557545

In [40]:
len(s)

872