In [1]:
import numpy as np
import pandas as pd

In [2]:
# in run_2c data....
# choose pairs to highlight: for each target, select the source w the highest raw_overlap baseline
# groupby target, source, compute mean of raw overlap_auc
# for ea. target, choose source w. higher mean

In [3]:
fn = 'run_2c/analysis/results.csv'
df = pd.read_csv(fn)
df['pair'] = df['source'] + '_' + df['target']
df.head()

  source target  seed  transfer  raw_published  raw_overlap      pair
0    REP   GDSC     0  0.723808       0.496935     0.592467  REP_GDSC
1    REP   GDSC     1  0.709801       0.514159     0.574744  REP_GDSC
2    REP   GDSC     2  0.761131       0.520504     0.573295  REP_GDSC
3    REP   GDSC     3  0.691812       0.491811     0.564582  REP_GDSC
4    REP   GDSC     4  0.758305       0.526826     0.623133  REP_GDSC

In [4]:
raw_mean_df = df[['pair', 'raw_overlap']].groupby('pair').mean().reset_index()
raw_mean_df = raw_mean_df.rename(columns={'raw_overlap': 'mean_raw_overlap'})
raw_mean_df

        pair  mean_raw_overlap
0  CTD2_GDSC          0.622027
1   CTD2_REP          0.604615
2  GDSC_CTD2          0.622027
3   GDSC_REP          0.596526
4   REP_CTD2          0.604615
5   REP_GDSC          0.596526

In [5]:
df = df.merge(raw_mean_df, on='pair')
df.head()

,source,target,seed,transfer,raw_published,raw_overlap,pair,mean_raw_overlap
0,REP,GDSC,0,0.723808,0.496935,0.592467,REP_GDSC,0.596526
1,REP,GDSC,1,0.709801,0.514159,0.574744,REP_GDSC,0.596526
2,REP,GDSC,2,0.761131,0.520504,0.573295,REP_GDSC,0.596526
3,REP,GDSC,3,0.691812,0.491811,0.564582,REP_GDSC,0.596526
4,REP,GDSC,4,0.758305,0.526826,0.623133,REP_GDSC,0.596526

In [6]:
highlight_pairs = ['CTD2_REP', 'CTD2_GDSC', 'GDSC_CTD2']